
FROM node:12.12.0

WORKDIR /app

COPY package.json package.json

RUN npm install

# // setting time zone to Los Angeles
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . ./

CMD ["node", "server.js"]